train_file: "datasets/sensor_data_train.csv"
test_file: "datasets/sensor_data_test.csv"
pred_file: "datasets/sensor_data_pred.csv"
alpha: 0.01
dist: "normal"
n_estimators: 500
learning_rate: 0.01
minibatch_frac: 1.0
col_sample: 1.0
# load_model_path: "models/model.pickle"
# save_model_path: "models/model2.pickle"
